version: "3.8"
services:
  fdlv-db:
    image: mysql:8.0
    container_name: fdlv-db
    restart: always
    ports:
      - "3306:3306"
    networks:
      - fdlv-net
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - fdlv-db:/var/lib/mysql
networks:
  fdlv-net:
volumes:
  fdlv-db: